name: Build
# The name of this workflow (Build) should be in sync with the test-e2e.yml workflow's workflow_run listener.


on:
  pull_request:
    paths-ignore:
    - 'CODE_OF_CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'SECURITY.md'
    - 'docs/**'
    - '.github/**'
    - '!.github/workflows/build.yml'
    - '!.github/workflows/test-e2e.yml'
  push:
    branches:
    - develop
    - main
    - release/*
    tags: '[0-9]+.[0-9]+.[0-9]+'
    paths-ignore:
    - 'CODE_OF_CONDUCT.md'
    - 'CONTRIBUTING.md'
    - 'LICENSE'
    - 'SECURITY.md'
    - 'docs/**'
    - '.github/**'
    - '!.github/workflows/build.yml'    
    - '!.github/workflows/test-e2e.yml'
  release:
    types:
    - created



# Keep this filename in sync with the filename environment variable (PR_AUTO_BUILD_FILE_NAME) in the testserver-deployment.yml workflow
# and with the build_workflow_name environment variable in the staging-deployment.yml workflow

jobs:
  define-inputs:
    name: Define Inputs
    runs-on: ubuntu-latest
    steps:
      - name: Build step
        run: |
          echo "test build"
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Upload Server Test Results
        uses: actions/upload-artifact@v4
        with:
          name: JUnit Test Results
          path: server-tests/*.xml
      - name: Upload Client Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Client JUnit Test Results
          path: client-tests/junit.xml

  # Save Docker image tag as an artifact
  save-docker-tag:
    name: Save Docker Image Tag
    needs: define-inputs
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker Tag to File
        run: |
          echo "pr-1564654" > docker-tag.txt
          echo "Using Docker tag: pr-1564654"
      - name: Upload Docker Tag as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-tag
          path: docker-tag.txt



