name: Deploy to test servers

asdasdsadsadadadadadadadadadadadsadadasdasdsadasdad
        description: "Which environment to deploy (e.g. artemis-test7.artemis.cit.tum.de, etc.)."
        required: true
        type: string
      HELIOS_BUILD:
        description: "Whether to also build or just deploy the existing Docker image"
        required: true
        type: boolean
        default: false
      HELIOS_BUILD_TAG:
        description: "Docker tag to use if we are building or pulling an existing image"
        required: false
        type: string
      HELIOS_RAW_URL:
        description: "URL to the raw content of the repository in the format https://raw.githubusercontent.com/:owner/:repo/:sha"
        required: false
        type: string
      branch_name:
        description: "Which branch to deploy"
        required: true
        type: string
      environment_name:
        description: "Which environment to deploy (environment defined in GitHub)"
        required: true
        type: string
      triggered_by:
        description: "Username that triggered deployment (not required, shown if triggered via GitHub UI, logged if triggered via GitHub app)"
        required: false
        type: string

asdasd"Environment: ${{ github.event.inputs.environment_name }}"
        echo "Triggered by?: ${{ github.event.inputs.triggered_by }}"

  deploy:
    environment: ${{ github.event.inputs.environment_name }}
    needs: conditional_build_job
    runs-on: ubuntu-latest
    steps:
asd

