name: Deploy to test servers


on:
  release:
    types:
    - created

concurrency: dev

jobs:
  conditional_build_job:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
        echo "Branch: asdasdsadadasd"
    #     echo "Environment: ${{ github.event.inputs.environment_name }}"
    #     echo "Triggered by?: ${{ github.event.inputs.triggered_by }}"
    # - name: Send greeting
    #   run: |
    #     echo "Branch: ${{ github.event.inputs.branch_name }}"
    #     sleep 15
    #     echo "Triggered by?: ${{ github.event.inputs.triggered_by }}"
    # - name: Send greeting
    #   run: |
    #     echo "Branch: ${{ github.event.inputs.branch_name }}"
    #     echo "Environment: ${{ github.event.inputs.environment_name }}"
    #     echo "Triggered by?: ${{ github.event.inputs.triggered_by }}"

  deploy:
    environment: dev
    needs: conditional_build_job
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: |
        echo "Deploying to asdasdasdasd"
        sleep 30 && exit 1

