name: Deploy to test servers


on:
  workflow_dispatch:
    inputs:
      HELIOS_TRIGGERED_BY:
        description: "The user who triggered the workflow"
        required: true
      HELIOS_BRANCH_NAME:
        description: "The branch name to deploy"
        required: true
      HELIOS_ENVIRONMENT_NAME:
        description: "The environment to deploy to"
        required: true
      HELIOS_BUILD:
        description: "Whether to build the project"
        required: true
      HELIOS_BUILD_TAG:
        description: "The build tag (if HELIOS_BUILD is true)"
        required: false

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
  conditional_build_job:
    runs-on: ubuntu-latest
    needs: print
    steps:
    - name: Send greeting
      run: echo "Hello"
    - name: Failing Step
      run: exit 1      
    - name: Set Failure Details
      if: failure()
      run: echo "failure_reason=Build failed at Step 1" >> $GITHUB_ENV
  deploy:
    environment: dev
    needs: conditional_build_job
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello"
