name: Deploy workflow


on:
  workflow_dispatch:
    inputs:
      HELIOS_TRIGGERED_BY:
        description: "The user who triggered the workflow"
        required: true
      HELIOS_BRANCH_NAME:
        description: "The branch name to deploy"
        required: true
      HELIOS_ENVIRONMENT_NAME:
        description: "The environment to deploy to"
        required: true
      HELIOS_BUILD:
        description: "Whether to build the project"
        required: true
      HELIOS_BUILD_TAG:
        description: "The build tag (if HELIOS_BUILD is true)"
        required: false

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: 'echo "payload: ${{ toJson(github.event.inputs) }}"'
    - name: Display inputs
      run: |
        echo "HELIOS_TRIGGERED_BY: ${{ github.event.inputs.HELIOS_TRIGGERED_BY }}"
        echo "HELIOS_BRANCH_NAME: ${{ github.event.inputs.HELIOS_BRANCH_NAME }}"
        echo "HELIOS_ENVIRONMENT_NAME: ${{ github.event.inputs.HELIOS_ENVIRONMENT_NAME }}"
        echo "HELIOS_BUILD: ${{ github.event.inputs.HELIOS_BUILD }}"
        echo "HELIOS_BUILD_TAG: ${{ github.event.inputs.HELIOS_BUILD_TAG }}"
        echo "inputs: ${{ github.event.inputs }}"
  conditional_build_job:
    runs-on: ubuntu-latest
    needs: print
    steps:
    - name: Send greeting
      run: echo "Hello"
  deploy:
    environment: dev
    needs: conditional_build_job
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello"
