name: Update helios-metadata-branch

on:
  push:
    branches:
      - main

jobs:
  update-metadata:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git User
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "actions@github.com"

    - name: Check if helios-metadata-branch exists
      id: check-branch
      run: |
        if git ls-remote --exit-code --heads origin helios-metadata-branch; then
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "exists=false" >> $GITHUB_ENV
        fi

    - name: Create helios-metadata-branch and clean files if it doesn't exist
      if: env.exists == 'false'
      run: |
        git checkout --orphan helios-metadata-branch
        rm -rf *
        echo "Branch created and cleaned."
        echo "Appending timestamp: $(date)" > metadata.txt
        git add metadata.txt
        git commit -m "Initialize helios-metadata-branch with metadata.txt"
        git push origin helios-metadata-branch --force

    - name: Checkout helios-metadata-branch
      if: env.exists == 'true'
      run: |
        git fetch origin helios-metadata-branch
        git checkout helios-metadata-branch

    - name: Create or append to metadata.txt
      if: env.exists == 'true'
      run: |
        FILE="metadata.txt"
        echo "Appending timestamp: $(date)" >> "$FILE"
        echo "Updated file content:"
        cat "$FILE"

    - name: Commit and push changes
      run: |
        git add metadata.txt
        git commit -m "Update metadata.txt with timestamp"
        git push origin helios-metadata-branch
