name: E2E Tests

on:
  workflow_run:
    # Must match the name of build.yml workflow.
    workflows: ["Build"]
    types: [completed]

concurrency:
  group: |
    ${{
      github.event.workflow_run.head_branch && format('e2e-{0}', github.event.workflow_run.head_branch)
      || github.event.workflow_run.event == 'release' && format('e2e-release-{0}', github.event.workflow_run.tag_name)
      || format('e2e-{0}', github.event.workflow_run.head_sha)
    }}
  cancel-in-progress: true

jobs:
  run-e2e:
    name: Run E2E Tests
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      (
        github.event.workflow_run.event == 'pull_request' ||
        github.event.workflow_run.event == 'push' && (
          github.event.workflow_run.head_branch == 'develop' ||
          github.event.workflow_run.head_branch == 'main' ||
          startsWith(github.event.workflow_run.head_branch, 'release/') ||
          github.event.workflow_run.head_branch == ''
        ) ||
        github.event.workflow_run.event == 'release'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Create pending status
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }}" \
            -d '{"state":"pending","context":"E2E Tests","description":"E2E tests are running...","target_url":"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
      - name: Echo concurrency group
        run: |
          CONCURRENCY_GROUP=$(echo "${{ 
            github.event.workflow_run.head_branch && format('e2e-{0}', github.event.workflow_run.head_branch)
            || github.event.workflow_run.event == 'release' && format('e2e-release-{0}', github.event.workflow_run.tag_name)
            || format('e2e-{0}', github.event.workflow_run.head_sha)
          }}")
          echo "Concurrency group: $CONCURRENCY_GROUP"
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Echo github.event
        run: echo '${{ toJSON(github.event) }}'
      - name: Echo github.event.workflow_run
        run: echo '${{ toJSON(github.event.workflow_run) }}'
      - name: Sleep
        run: sleep 30 && exit 1
      - name: Parse test results and update status
        if: always()
        run: |
          # Determine workflow status
          WORKFLOW_STATUS="${{ job.status }}"
          
          # Default values for metrics
          TOTAL=0
          PASSED=0
          FAILED=0
          SKIPPED=0
          
          # Check if test results file exists
          XML_FILE="src/test/playwright/test-reports/results.xml"
          if [ -f "$XML_FILE" ]; then
            # Sum the totals for all testsuites
            TESTS_COUNT=$(grep -o 'tests="[0-9]*"' "$XML_FILE" | grep -o '[0-9]*' | awk '{sum+=$1} END {print sum}')
            FAILURES_COUNT=$(grep -o 'failures="[0-9]*"' "$XML_FILE" | grep -o '[0-9]*' | awk '{sum+=$1} END {print sum}')
            SKIPPED_COUNT=$(grep -o 'skipped="[0-9]*"' "$XML_FILE" | grep -o '[0-9]*' | awk '{sum+=$1} END {print sum}')
            
            # Use values if counts were found
            if [ -n "$TESTS_COUNT" ]; then TOTAL=$TESTS_COUNT; fi
            if [ -n "$FAILURES_COUNT" ]; then FAILED=$FAILURES_COUNT; fi
            if [ -n "$SKIPPED_COUNT" ]; then SKIPPED=$SKIPPED_COUNT; fi
            
            # Calculate passed tests
            PASSED=$((TOTAL - FAILED - SKIPPED))
            
            echo "XML Parsing Results:"
            echo "Total: $TOTAL"
            echo "Failed: $FAILED" 
            echo "Skipped: $SKIPPED"
            echo "Passed: $PASSED"
          fi
          
          # Determine GitHub status state based on workflow status
          if [ "$WORKFLOW_STATUS" = "success" ]; then
            STATE="success"
            DESCRIPTION="✅ E2E tests passed: $PASSED passed, $FAILED failed, $SKIPPED skipped"
          elif [ "$WORKFLOW_STATUS" = "failure" ]; then
            STATE="failure"
            DESCRIPTION="❌ E2E tests failed: $PASSED passed, $FAILED failed, $SKIPPED skipped"
          else
            STATE="error"
            DESCRIPTION="⚠️ E2E tests encountered an error"
          fi

          DESCRIPTION_ESCAPED=$(echo "$DESCRIPTION" | sed 's/"/\\"/g')
          JSON_PAYLOAD="{\"state\":\"$STATE\",\"context\":\"E2E Tests\",\"description\":\"$DESCRIPTION_ESCAPED\",\"target_url\":\"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
          echo "JSON payload: $JSON_PAYLOAD"
          
          # Update status
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_sha }}" \
            -d "$JSON_PAYLOAD"

