name: E2E Tests

on:
  workflow_run:
    # Must match the name of build.yml workflow.
    workflows: ["Build"]
    types: [completed]

concurrency:
  group: |
    ${{
      github.event.workflow_run.head_branch && format('e2e-{0}', github.event.workflow_run.head_branch)[0:400]
      || github.event.workflow_run.event == 'release' && format('e2e-release-{0}', github.event.workflow_run.tag_name)[0:400]
      || format('e2e-{0}', github.event.workflow_run.head_sha)[0:400]
    }}
  cancel-in-progress: true

jobs:
  run-e2e:
    name: Run E2E Tests
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      (
        github.event.workflow_run.event == 'pull_request' ||
        github.event.workflow_run.event == 'push' && (
          github.event.workflow_run.head_branch == 'develop' ||
          github.event.workflow_run.head_branch == 'main' ||
          startsWith(github.event.workflow_run.head_branch, 'release/') ||
          github.event.workflow_run.head_branch == ''
        ) ||
        github.event.workflow_run.event == 'release'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      - name: Echo github.event
        run: echo '${{ toJSON(github.event) }}'
      - name: Echo github.event.workflow_run
        run: echo '${{ toJSON(github.event.workflow_run) }}'
